# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/thirdparty/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/thirdparty

PRODUCT_COPY_FILES += \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass_aac.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass_aac.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass_ape.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass_ape.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass_aso.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass_aso.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass_fx.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass_fx.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass_mpc.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass_mpc.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass_ssl.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass_ssl.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbass_tta.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbass_tta.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbassalac.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbassalac.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbassdsd.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbassdsd.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbassflac.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbassflac.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbasshls.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbasshls.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbassmix.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbassmix.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbassopus.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbassopus.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbasswebm.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbasswebm.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libbasswv.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libbasswv.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libcolorutils.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libcolorutils.so \
    vendor/thirdparty/proprietary/product/app/AIMP/lib/arm64/libsamba.so:$(TARGET_COPY_OUT_PRODUCT)/app/AIMP/lib/arm64/libsamba.so \
    vendor/thirdparty/proprietary/product/bin/adb:$(TARGET_COPY_OUT_PRODUCT)/bin/adb \
    vendor/thirdparty/proprietary/product/bin/adb.bin:$(TARGET_COPY_OUT_PRODUCT)/bin/adb.bin \
    vendor/thirdparty/proprietary/product/bin/fastboot:$(TARGET_COPY_OUT_PRODUCT)/bin/fastboot \
    vendor/thirdparty/proprietary/product/etc/permissions/privapp-permissions-com.aimp.player.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.aimp.player.xml \
    vendor/thirdparty/proprietary/product/etc/sysconfig/com.aimp.player-hiddenapi-package-whitelist.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/com.aimp.player-hiddenapi-package-whitelist.xml

PRODUCT_PACKAGES += \
    AIMP \
    GeometricWeather \
    RootExplorer \
    SimpleCalendar \
    Via
